### ISSUE TITLE
ignore branch is not working with regex

### ISSUE THREAD

**Issue by csnyder78** [Eernie/bitbucket-webhooks-plugin#104]
We have 3 branches on our repo and have setup a  different webhook for each.  We are using the regex ^(?!develop$).*$    which should by our understanding ignore all except develop branch and only send that specific webhook.  However, all 3 webhooks that we have are sending.  Is there something that we are missing?

**Comment by casz** [comment]
@csnyder78 the ignore branch does not support regex. I would welcome contributions 👍 
https://github.com/Eernie/bitbucket-webhooks-plugin/blob/f4a49036182f320a289876e36ed277fec9482fbe/src/main/java/nl/eernie/bitbucket/events/BitbucketPushEvent.java#L76-L85

**Comment by csnyder78** [comment]
@casz that's very unfortunate, we have many branches in our repos, only ignoring one is not a very good solution.  I'm afraid I do not code or I would be happy to help.  I  only do a little scripting :/

**Comment by casz** [comment]
Looking at the code again @csnyder78 it uses `String.matches` that takes a Java regex pattern but I think your regex pattern is incorrect in according to what you wanted to achieve.

`^(?!develop$).*` should be the correct one.

You should be able to add additional unit tests to this project to confirm.

https://regex101.com/r/FZrCnx/1

**Comment by csnyder78** [comment]
hey,  that worked great!  Thanks for helping me out there.

**Comment by tlenex** [comment]
how I could ignore all but `release/qa1` branch?
`^(?!release\/qa1$).*` does not seem to work, when tools like https://www.freeformatter.com/java-regex-tester.html#ad-output tell me that it should.
