### ISSUE TITLE
JSONObject["user"] not found ERROR

### ISSUE THREAD

**Issue by GradyD** [Eernie/bitbucket-webhooks-plugin#105]
Bitbucket is sending over the json but jenkins is not processing it. Looking at the logs I am getting a JSONObject["user"] not found error

Received commit hook notification for {"scmId":"git","project":{"key":"CBS","name":"My private project"},"slug":"corporate","links":{"self":[{"href":"https://git.xxxx.com/projects/CBS/repos/corporate/browse"}]},"fullName":"CBS/corporate","ownerName":"CBS","public":false,"owner":{"username":"CBS","displayName":"CBS"}}
Jun 06, 2018 11:05:35 PM WARNING org.eclipse.jetty.server.handler.ContextHandler$Context log
Error while serving https://ci.xxxxxxx.com/bitbucket-hook/
net.sf.json.JSONException: JSONObject["user"] not found.

Can you tell me what needs to happen to resolve this error?

**Comment by casz** [comment]
Not sure I can understand, what it is your reporting.

Is the error message taken from Bitbucket or Jenkins? Seems like the error message is from Jenkins. the url does not look like you are using the correct plugin for this webhook plugin.

Which plugin are you using on Jenkins?
You should be using [Bitbucket Branch Source plugin](https://plugins.jenkins.io/cloudbees-bitbucket-branch-source) for best integration possible.

**Comment by GradyD** [comment]
Sorry I thought this was fixed but I have narrowed down the problem.

I am using this plugin on bitbucket 4.14.7 and it starts a build when I have the "On Push" repo event selected and make a commit.

For the PR events it does not appear to be starting a build at all.
![image](https://user-images.githubusercontent.com/994964/41098549-c8a81204-6a29-11e8-98d9-9fb81518f378.png)
![image](https://user-images.githubusercontent.com/994964/41098568-da80c188-6a29-11e8-8a05-84549c2bdd6d.png)

Sadly, neither of these actions triggered a build and I do not see any errors on the jenkins side of things.

**Comment by casz** [comment]
In Jenkins your using a Bitbucket project job type? And you have setup your bitbucket server as a bitbucket endpoint and enabled managed hooks in jenkins global settings?

Did you try and hit scan after creating the bitbucket project job type? and see it creating builds for you?

**Comment by GradyD** [comment]
I am using a freestyle project.

I have setup by Bitbucket endPoint in the global settings and it does have the "Manage Hooks" checked.

Will this not work with freestyle projects?

**Comment by casz** [comment]
No this will not work with freestyle jobs. Bitbucket branch source plugin relies on Jenkinsfile.

**Comment by GradyD** [comment]
Ahh perfect. Thank you for the added clarification.

**Comment by casz** [comment]
If you choose to switch to Jenkinsfile, the webhook plugin and the bitbucket branch source plugin will work in tandem and be able to detect new branches, tags and PRs automatically as long as Jenkinsfile is present in the repository 😄
