### ISSUE TITLE
Pull Request Updated is checked, but still not triggering a build when pr is updated.

### ISSUE THREAD

**Issue by Vatsaldhar26** [Eernie/bitbucket-webhooks-plugin#108]
<img width="368" alt="screen shot 2018-07-19 at 12 01 21 pm" src="https://user-images.githubusercontent.com/35141195/42925346-8847a768-8b4b-11e8-86ab-a283abb85e76.png">

This is how I have configured, but whenever we have a pull request updated build is not being generated same for pull request commented. But for Pull request created it is working fine.

I am using Jenkins 2.129
The version for webhook which I am using is 1.6.3
Yes, I am using bitbucket branch source plugin.
Yes, I am also using the Bitbucket project/Team project type in Jenkins.

Below is my  Bitbucket project/Team project setup.

<img width="940" alt="screen shot 2018-07-19 at 4 44 12 pm" src="https://user-images.githubusercontent.com/35141195/42939415-3318a01c-8b73-11e8-91de-e6018b773263.png">

**Comment by casz** [comment]
- Are you using Jenkins?
- What version of webhook plugin are you using?
- Are you using Bitbucket Branch Source plugin?
- Are you using the Bitbucket project/team project type in Jenkins?

The more detailed a issue is the better I can assist.

**Comment by Vatsaldhar26** [comment]
I have updated, you can have a look at it again.

**Comment by casz** [comment]
Since your calling it stash... What version of bitbucket are you using? 😐

**Comment by Vatsaldhar26** [comment]
Sorry, i missed that part. I am on v5.0.2 of stash.

**Comment by casz** [comment]
Can you try and look into or show me the events for a specific project in Jenkins.
Besides the scan log there should be an events log

**Comment by casz** [comment]
Definitely what I was asking for :)

**Comment by casz** [comment]
is the PR coming from a fork or is it on a origin which is `~DHARVA`

**Comment by Vatsaldhar26** [comment]
PR is from ~DHARVA itself, from one branch to master and the PR number is PR-6.

**Comment by casz** [comment]
Checking PR-6 from ~DHARVA/sca-analyser and branch feature/CI-68-unit-testing-and-performance-test
Does not have a Jenkinsfile... 👍 According to the events log

**Comment by casz** [comment]
If you notice PR-11 which have a Jenkinsfile
```
Checking PR-11 from ~DHARVA/sca-analyser and branch feature/CI-90-creating-serialised-file-of-dependency
      ‘Jenkinsfile’ found
    Met criteria
Scheduled build for branch: PR-11
```

**Comment by casz** [comment]
You might want to rebase your PR-6 on top of master 😄

**Comment by Vatsaldhar26** [comment]
Which I quite strange since I Do have Jenkins file in PR-6

**Comment by Vatsaldhar26** [comment]
So Let's say if Update PR-11, will it build that pull request? Trying rn this

**Comment by casz** [comment]
Hmm then your behaviours is excluding each other out. I currently don't use bitbucket so play around the with the traits

**Comment by Vatsaldhar26** [comment]
So is there any blog which you might to suggest which can suggest the right way to setup all this?

**Comment by Vatsaldhar26** [comment]
And also how can i check the Request content which is being sent out to Jenkins, when pull request thing happens?

**Comment by Vatsaldhar26** [comment]
As I see, Build is being triggered only when a pull request is created and not in any pull request events case.

**Comment by netwiser** [comment]
Hi There,
I have the same issue now. I am using the webhook plugin 1.6.2 and check the pull request updated checkbox but can not receive any event from bitbucket server. The postb.in I am using is http://postb.in/b/VuT6uk1g. I have push quite a few commit to the opened PR but nothing received. I also test with the requestbin.fullcontact.com got the same result.

The bitbucket server I am using is 5.8.1, the webhook plugin is v1.6.2.  Should I upgrade to 1.6.3?
