### ISSUE TITLE
Bitbucket to MS Teams webhook gives 'Something went wrong' message

### ISSUE THREAD

**Issue by GitMje** [Eernie/bitbucket-webhooks-plugin#109]
First off, thank you to those that created this plugin and support it, this is the nicest bb webhook plugin out there that I've found with a lot finer control over the types of triggers (pull requests/push/etc). 

We have recently installed this plugin, but it does not seem to be working with our MS Team channel.  In looking at the logs on the bb server, it looks like it is showing the following (note, I've REDACTED potentially sensitive information):
`Something went wrong while posting (response code:400) the following body to webhook: [generic_webhook(https://outlook.office.com/webhook/REDACTED)] 
{"actor":{"username":"merpenbeck","displayName":"Michael Erpenbeck"},"repository":{"scmId":"git","project":{"key":"DEVOPS","name":"DevOps"},"slug":"continuous.learning","links":{"self":[{"href":"URL_REDACTED"}]},"public":false,"owner":{"username":"DEVOPS","displayName":"DEVOPS"},"ownerName":"DEVOPS","fullName":"DEVOPS/continuous.learning"},"push":{"changes":[{"created":false,"closed":false,"new":{"type":"branch","name":"master","target":{"type":"commit","hash":"REDACTED"}},"old":{"type":"branch","name":"master","target":{"type":"commit","hash":"REDACTED"}}}]}}
`
When researching this, I came upon this [post](https://groups.google.com/forum/#!topic/jenkinsci-users/AZi6_kcr2sI) which seemed similar.  I took the recommended solution and upgraded to the latest version of the plugin, with no change in behavior.

I decided to debug the issue a bit further and used Postman to POST the same request to get the details on the 400 error.  It resulted in a 400 error as well, with a response of 'Summary or Text is required'.  If I add `"text": "hello world",` to the beginning of the json, I will see "hello world" appear in the MS Teams channel, but nothing else.
![postman_result](https://user-images.githubusercontent.com/8420128/42984546-af9fe232-8bb2-11e8-85c2-d8873fa00650.png)

I have tried this with both a Bitbucket webhook connector in MS Teams and an Incoming webhook connector and I get the same result.  Perhaps there's a different connector that would understand the json format?  Or perhaps I'd need to change the payload of the json for this plugin to format and embed the json data into a new "text" field so that MS Teams will display it?

I apologize if I am missing anything basic or obvious as I am not very experienced with debugging webhooks.  Any suggestions are welcome on how to resolve this.

The details of what we are using are below (note I've also added some of the other plugins in case there are known side-effects):
- Bitbucket Server v5.9.0
- plugin: bitbucket-webhooks v1.6.3
- other plugin: Bitbucket Web Post Hooks Plugin v3.1.0
- other plugin: Office 365 Connector v2.0

**Comment by casz** [comment]
We don't support sending webhooks to office 365. What you could do is build an webhook listener that resends the information in a format that office 365 understands.

or

You could contribute a PR to this plugin that changes the webhook type when the webhook URL is going to `office.com`

**Comment by casz** [comment]
See https://github.com/jenkinsci/office-365-connector-plugin on how to send webhooks to office 365.

**Comment by GitMje** [comment]
@casz  Thank you so much for your quick response.  We have investigated the office-365 connector plugin. The bitbucket plugin is not as fully functioning as this one is, but we will use the office-365 connector instead.

I will also look at building the webhook listener.

Thanks again.
