### ISSUE TITLE
Is there any Environment variable associated with this plugin, which gives name of the branch from which the build was triggered?

### ISSUE THREAD

**Issue by Vatsaldhar26** [Eernie/bitbucket-webhooks-plugin#113]
I hope i am clear with above description.

**Comment by casz** [comment]
this is a question that should be asked/answered in Jenkins users mailing list but there definitely is one.

**Comment by Vatsaldhar26** [comment]
Well, thanks for that. What basically I am trying to do is to get the name of the branch in the Jenkins pipeline itself using some kind of variable. As I know that a JSON file is sent from bitbucket side to Jenkins and that does have a info about the branch, how can i have that info while running the pipeline script? any help appriciated
