### ISSUE TITLE
How to setup for a Multibranch job , On  pull request  the jenkins build should trigger ? 

### ISSUE THREAD

**Issue by abhisek171** [Eernie/bitbucket-webhooks-plugin#114]
Please provide the steps , I am unable to achieve this . in Multibranch pipeline.

**Comment by abhisek171** [comment]
Atlassian Bitbucket v5.8.3,
Jenkins ver. 2.46.3.

Set up done : 

Given the Bitbucket ed point in manage jenkins --> configure settings --> Bb end points.
web-hok settings in post web hook settings . added the jenkins url . 
while configuring a job I am still confused what to add and what not to add. 

so kindly help me out here.

**Comment by casz** [comment]
This is a question for the Jenkins user mailing list. However if you search through some of the issue you will find the answer as well

**Comment by casz** [comment]
You should be using the bitbucket branch source plugin
