### ISSUE TITLE
Plugin is not marked in Atlassian Marketplace as compatible with Bitbucket Datacenter

### ISSUE THREAD

**Issue by filipowm** [Eernie/bitbucket-webhooks-plugin#117]
Hi,
We are having issue that we cannot install plugin on our Bitbucket Datacenter, because in Marketplace it is marked as not compatible with Datacenter version. 

It is despite `<param name="atlassian-data-center-compatible">true</param>` is configured in `atlassian-plugin.xml`.

As per Atlassian documentation [here](https://developer.atlassian.com/platform/marketplace/dc-apps-submitting-your-app/) also `<param name="atlassian-data-center-status">compatible</param>` should be set.

Plugin should be also checked with [Developing Datacenter plugin guidelines](https://developer.atlassian.com/platform/marketplace/guidelines-for-data-center-app-development).

**Comment by casz** [comment]
@filipowm I have uploaded the OBR directly to GitHub since Atlassian refuses to approve the app for the bitbucket data center in their Atlassian marketplace

**Comment by casz** [comment]
Closing, see https://github.com/Eernie/bitbucket-webhooks-plugin/issues/127#issuecomment-466663550
