### ISSUE TITLE
Option "Pull Request Updated" is ignored / has no effect

### ISSUE THREAD

**Issue by Iridias** [Eernie/bitbucket-webhooks-plugin#120]
Related to:
#108 

When updating a pull-request with this option enabled, no request is sent against the specified URL. I see no request in my nginx-access log and also nothing in the atlassian-bitbucket.log!
On the other hand, the option "Pull request commented" works as expected.

Plugin-Version: 1.6.3
BitBucket Version: 5.14.1

**Comment by casz** [comment]
Can you confirm that the PR update event is sent, you can use something like: https://webhook.site

**Comment by Iridias** [comment]
Hmm, ok - my bad.
Seems the problem is with atlassian/BitBucket: https://jira.atlassian.com/browse/BSERV-10279

Then it might be a good idea to rename this option to "Pull request description updated" - at least thats what the hint on the corresponding field for the build-in webhooks suggests.

**Comment by casz** [comment]
if your using the built-in webhook support that is not this plugin 🙈

**Comment by Iridias** [comment]
I know. What I meant to say is, that it looks, like BitBucket has no internal event for PR-updates.
Checking the behaviour of the build-in webhook, was just a quick way to compare the behaviour of bitbucket with this plugin.
Because I don't know how to check which events BitBuckets sends to its plugins internally.
Don't know how an external site like webhook.site can help in this regard.

**Comment by casz** [comment]
In the plugin you can register the webhook and point to the url you were given by https://webhook.site/ it's a debug where you can see the output of the webhook.

![image](https://user-images.githubusercontent.com/1661688/46882342-9d804400-ce4e-11e8-879f-b1d0dd13336b.png)

**Comment by casz** [comment]
PR updated means when you push code to the PR it will sent an event.

**Comment by Iridias** [comment]
I'm not quite sure what you mean. In the admin-panel of bitbucket, the manage-plugin site offers no settings for this plugin. And I can't imagine, that you want me to just change the URL of the post-webhook I created for my project. 
Because as pointed out in my first comment, its currently pointing to my webservers reverse-proxy (nginx) and no matter what the plugin would send - it would be looged in the access.log. But there is no request whatsoever. 
IMO its required to debug, which events (if any) bitbucket sends to its registered event-listeners when a PR gets updated (code-wise). The linked upstream-issue implies, thats its not sending any event in this case. But I have no experience in writing bitbucket-plugins, so I have currently no option to verify this.

**Comment by Iridias** [comment]
So, I had a more detailed look into the development docs of atlassian bitbucket, and I was right:
https://docs.atlassian.com/bitbucket-server/javadoc/5.14.1/api/reference/com/atlassian/bitbucket/event/pull/PullRequestUpdatedEvent.html

This is the event the plugin listens for in the PullRequestListener - see the available fields/getters in the event: previousDescription, previousTitle and previousToBranch. And the documentation of this class is very clear: "Event that is raised when the pull request title, description, or target branch are updated."

Also have a look at all available PullRequest-Events!
Notice, that there is no other Event for updates.

So this trigger can't work on BitBucket Server - and never has.
I guess it will work on BitBuckt Cloud though, as its a different product.

**Comment by casz** [comment]
In anycase this plugin offers you a settings page on each repository there you can setup webhooks to trigger on the different events and you can have multiple webhooks.

**Comment by Iridias** [comment]
I created a pull-request: https://github.com/Eernie/bitbucket-webhooks-plugin/pull/121
I guess, for now, this issue can be closed with "needs fix upstream"

**Comment by jsdevel** [comment]
I was facing exactly this same problem, and thanks to the investigative work of @Iridias, came across this:

https://docs.atlassian.com/bitbucket-server/javadoc/5.14.1/api/reference/com/atlassian/bitbucket/event/pull/PullRequestRescopedEvent.html

Here's the relevant section:

> Event that is raised when the ref for the source-branch and/or the target-branch of a pull request is updated. Note that this does not necessarily mean that the list of commits that the pull request covers will change.

Has anyone tried this even to see if the old "Pull request updated" semantics could be fixed?  This plugin is quite useless without the ability to trigger a build on both PR creation and update tbh.

**Comment by casz** [comment]
@jsdevel your welcome to contribute :smile:

**Comment by jsdevel** [comment]
@casz there's actually no need for me to contribute :)  The plugin is _already_ handling the PullRequestRescopedEvent.  I may open a PR to update the legends for the checkboxes.

**Comment by MaroonedMind** [comment]
So the issue is on plugin side after all? I have tried testing it with https://webhook.site/ – no requests are logged. Pull Request events don't trigger builds, only Push event does. I'm using Bitbucket v4.14.7

**Comment by jsdevel** [comment]
try the rescoped event @MaroonedMind

**Comment by MaroonedMind** [comment]
Thank you very much @jsdevel, it works! Didn't think "pull request updated" relates to description and title changes as opposed to commits. This naming strategy is quite confusing, especially since Bitbucket itself uses "Updated" flair to mark new commits.

**Comment by jsdevel** [comment]
@MaroonedMind you're welcome!  yea, it was confusing for me too, but actually makes sense.
