### ISSUE TITLE
Jenkins Job Git SCM Configurations for Pull Requests

### ISSUE THREAD

**Issue by dadadan23** [Eernie/bitbucket-webhooks-plugin#128]
Greetings

We are using this plugin with success between Bitbucket and Jenkins for non-pull requests, where a specific branch is configured in Jenkins.

However, we would like to trigger a unique set of jobs (such as a mavenJob) in Jenkins via the same trigger for a Bitbucket repo which has a pull request opened for it.  

The only way I have seem this work successfully so far is by enforcing that users create a feature branch with a prefix (ie. feature/, bugfix/) - but this is still resulting in jobs running on the feature branch when there is no pull request raised for it yet.

This is confusing because the configuration of this Bitbucket hook clearly indicates that it will fire based on pull request events in bitbucket.

Is there a Git SCM configuration that you might recommend I use for:
refspec
branch

... so that a job for a given repo will fire for a given commit if it is on a branch with a pull request raised against it.

I had not found any documentation for this plugin with recommendations on how to configure Jenkins in this use case.  Or, does this plugin only work with multibranchpipeline jobs in Jenkins when it comes to pull requests?

Thank you for your time, and assistance in clarifying how the systems should be configured for successful integration.

**Comment by casz** [comment]
All this is configurable in the bitbucket branch source plugin in Jenkins.

**Comment by dadadan23** [comment]
@casz can you be a little more specific?  I am not sure where I can see the branch/refspec I should be configuring my mavenJob to be looking for.  

The job is getting triggered - but its not finding anything to build.

Are you saying that I can only use job types which use the Bitbucket branch source, and cannot use the git scm as a source?

**Comment by casz** [comment]
I would not recommend using a Maven job, that is some legacy job type. 
Please use the bitbucket team/project job type: https://go.cloudbees.com/docs/plugins/bitbucket/

Bitbucket branch source plugin requires you to use Jenkins file.
https://jenkins.io/doc/book/pipeline/jenkinsfile/

I can't guide you on maven jobs.

**Comment by dadadan23** [comment]
Thank you @casz - that is very useful confirmation.

I'll reconsider my approach with the jobs we are running and move over to consider using the multibranchPipelineJob job type per that reference.
