### ISSUE TITLE
Repository events/Build Status triggers multiple times (3)

### ISSUE THREAD

**Issue by KafkaPalazzo** [Eernie/bitbucket-webhooks-plugin#129]
Hello,

Bitbucket ver: Atlassian Bitbucket v5.2.2
Plugin ver: 1.62

The Problem:
Upon build status update, the hook is triggered 3 times in succession, without even waiting for a response it seems.
This behavior is only seen with the Repository events/Build Status trigger.
Other triggers tested are Repository events/On push and Pull request events/Pull request created.

The POST URL is reaching a cherrypy REST API end point.
 
Am I missing something? Is it a known issue that was fixed in ver 1.63?

Thnx for the help,
KP

**Comment by KafkaPalazzo** [comment]
Update: upgraded to ver 1.63, issue persists.

**Comment by casz** [comment]
Could you log the three webhooks that are sent?
You could use something like https://webhook.site adding the unique ID you get and add it to the webhook plugin inside bitbucket repo config

![image](https://user-images.githubusercontent.com/1661688/54739345-0b782680-4bb8-11e9-8ec2-069fd2bd5770.png)

Thank you

**Comment by KafkaPalazzo** [comment]
Hey, for some reason the POST requests from the webhook don't reach the https://webhook.site, but they do reach the cherrypy server I'm running. Other requests sent via Postman do reach https://webhook.site

**Comment by casz** [comment]
webhook.site was just a suggestion 😅 if you have something else to capture it please do share 😄

**Comment by KafkaPalazzo** [comment]
![body](https://user-images.githubusercontent.com/44134583/54750366-12b32a80-4be0-11e9-96ae-2f59a62c68ee.jpg)
![configs_handler](https://user-images.githubusercontent.com/44134583/54750367-12b32a80-4be0-11e9-8914-eccfbdd64041.jpg)
![headers](https://user-images.githubusercontent.com/44134583/54750368-12b32a80-4be0-11e9-92ad-4f73bfdeeaad.jpg)
![hooks](https://user-images.githubusercontent.com/44134583/54750369-134bc100-4be0-11e9-85c4-539d1d1ddee4.jpg)
![tools](https://user-images.githubusercontent.com/44134583/54750370-134bc100-4be0-11e9-8b38-7ef32633228c.jpg)

Until I figure out why the Bitbucket  webhooks don't reach the servers, hope this data helps.
I noticed that if I add the Content-Length header in Postman, it also causes the requests not to reach the servers. So far I tried  https://webhook.site, https://pipedream.com, and requestbin.

**Comment by KafkaPalazzo** [comment]
It seems the trigger activates 3 times in a row, irregardless to what's happening in the end point, even if the method contains only a return statement.

Is there something special about the Build Status event?

**Comment by casz** [comment]
Oh thank you for going deep and using a debugger to find the issue, much appreciated, I will take a look at it 😄

**Comment by casz** [comment]
The code relies on bitbucket's event listeners so I would go as far to point my finger at internal bitbucket code that is not open source, so 🤷‍♂️.

I will see what I can do, but it might be specific to the bitbucket version your using it is quite dated.

**Comment by KafkaPalazzo** [comment]
Found the issue, it was related to one of our wrapper modules used to send requests to Bitbucket. The REST API to update the build status was actually triggered 3 times.

Sorry for the false alarm and thank you very much for your time and efforts,
KP

**Comment by casz** [comment]
Good, that you found it and avoided me wasting time 😅
