### ISSUE TITLE
Option to ignore a list of commiters

### ISSUE THREAD

**Issue by marbon87** [Eernie/bitbucket-webhooks-plugin#37]
Please add an option define a list of commiters, which commits should not trigger a webhook.
We use the maven release plugin for our releases that does two commits for each releases.

**Comment by Eernie** [comment]
I know the problem, maybe for now ( cause I don't have much time to implement this ): you can set the push argument to false, this will allows you to push the two commits in one push.

**Comment by mcneary70** [comment]
I agree that this would be a good feature to support, but in my case (multibranch pipeline jobs in Jenkins) it will involve work from other projects as well.

**Comment by marbon87** [comment]
I created a pull-request that implements this feature. It's simple but it works :)

**Comment by casz** [comment]
Fixed in 1.5.0
