### ISSUE TITLE
Merge event

### ISSUE THREAD

**Issue by RaviH** [Eernie/bitbucket-webhooks-plugin#45]
Hi,

I want to receive only merge events. Is their a way to do that or differentiate a merge event?

Regards,
Ravi Hasija

**Comment by casz** [comment]
This will be possible after #40 is included in a release 👍

**Comment by RaviH** [comment]
Hi Casz,

Any ETA on when  #40 would be merged?

**Comment by RaviH** [comment]
Until #40 is released: would I receive all events? And if so, can I check for merge events by checking the header: `pullrequest:fulfilled`?

**Comment by casz** [comment]
Fixed in 1.5.0
