### ISSUE TITLE
Compatibility between Bitbucket add-on and Jenkins plug-in

### ISSUE THREAD

**Issue by luka5z** [Eernie/bitbucket-webhooks-plugin#48]
When installing 1.4.2 version of Bitbucket add-on, does it has any compatibility requirements regarding Jenkins version or its plug-ins? Or can I upgrade "Post Webhooks for Bitbucket" without worrying abut Jenkins?

**Comment by casz** [comment]
You can safely upgrade. If something ever broke we would fix as soon as possible over at https://github.com/jenkinsci/bitbucket-branch-source-plugin or here.
