### ISSUE TITLE
Stop publishing webhooks on event threads

### ISSUE THREAD

**Issue by bturner** [Eernie/bitbucket-webhooks-plugin#54]
I'm the principal developer for Bitbucket Server.

Bitbucket Server has a constrained number of threads which handle invoking `@EventListener` methods (by default 1 per CPU core), and limits the pending event queue. Event listeners should not perform expensive operations directly; they should offload such processing to an `ExecutorService` or other mechanism so they can release the event thread as quickly as possible.

In addition to actually performing HTTP requests directly on the event thread, `PullRequestListener.rescopedEvent` is calling `PullRequestService.canMerge` on the event thread. If the pull request's refs are not up-to-date on disk, this may trigger a full `git merge` to update them (The `rescopedEvent` handler is explicitly seeking that behavior, actually), and before that can be done a _cluster-wide_ lock must be acquired. For Data Center customers, this is _extremely likely_ to trigger event thread starvation and can significantly impact many other operations.

This plugin can either create and manage its own `ExecutorService`, to allow it to control concurrency, or it can simply add an `@ComponentImport ExecutorService executorService` constructor parameter on listeners and use the one the host application exports for plugin developers. (That `ExecutorService` is also exported for the `Executor` and `ScheduledExecutorService` interfaces; you can `@ComponentImport` whichever you prefer.) The `ExecutorService` provided by the host application automatically propagates some state from the submitting thread to the executor thread that processes the operation (for example, the authenticated user and request details). To get the same special handling for your own `ExecutorService` you'll need to `@ComponentImport` SAL's `ThreadLocalDelegateExecutorFactory` and use the appropriate factory method to wrap your `ExecutorService`.

Please let me know if you have any questions, or if there's anything I can do to facilitate!

**Comment by bturner** [comment]
#57 includes fixes for this issue.

**Comment by casz** [comment]
Fixed in 1.5.0 👍
