### ISSUE TITLE
WebHookConfiguration.getRepositoryId() is not indexed

### ISSUE THREAD

**Issue by bturner** [Eernie/bitbucket-webhooks-plugin#58]
`WebHookConfiguration.getRepositoryId()` (the `REPO_ID` column) is not indexed. Since it appears first in the `WHERE` clause for all queries, adding an index on that column would prevent a full table scan when loading configurations to display or trigger webhooks.

**Comment by bturner** [comment]
#57 adds `@Indexed` to `getRepositoryId()`

**Comment by casz** [comment]
Fixed in 1.5.0 👍
