### ISSUE TITLE
WebHookConfigurations are not removed when repositories are deleted

### ISSUE THREAD

**Issue by bturner** [Eernie/bitbucket-webhooks-plugin#59]
This leaves rows behind in the `WebHookConfiguration` table, which further slow down the full table scans performed for every query (see #58).

The plugin should listen for `RepositoryDeletionRequestedEvent` and delete any rows for the repository which is being deleted. Repository IDs are never reused, so there's no chance a subsequent repository will ever reuse the existing configuration; it's "just" noise in the database.

**Comment by bturner** [comment]
#57 adds handling for `RepositoryDeletionRequestedEvent` and deletes `WebHookConfiguration` rows as part of the deletion transaction.

**Comment by casz** [comment]
Fixed in 1.5.0 👍
