### ISSUE TITLE
Unable to select where this sends out json messages to

### ISSUE THREAD

**Issue by mabushey** [Eernie/bitbucket-webhooks-plugin#63]
`This is the Webhooks plugin, It sends out json messages when a PR is created`

How do you configure where to send the json messages to?

**Comment by casz** [comment]
Under Webhooks inside repository settings.
![image](https://user-images.githubusercontent.com/1661688/29541653-c2e2298c-86d5-11e7-99f0-5f44bc48b3be.png)

**Comment by mabushey** [comment]
Wow that was fast @casz , thank you. I did set up a webhook there with `https://myserver/bitbucket-hook/`, but Jenkins didn't do anything after I pushed up a change to a branch so I assumed that was not the right place. I have Bitbucket 4.14.2 w/bitbucket-webhooks 1.4.2, Jenkins 2.74, Bitbucket Branch Source Plugin 2.2.3, Bitbucket Plugin 1.1.5. I am using a multibranch pipeline.

**Comment by casz** [comment]
@mabushey that's the incorrect webhook path.

https://myserver/bitbucket-scmsource-hook/notify

You should be able to use auto register inside jenkins to avoid setting up the webhook before Jenkins can get events from bitbucket

**Comment by casz** [comment]
Would recommend removing Bitbucket plugin and keep Bitbucket Branch Source plugin 👍

**Comment by mabushey** [comment]
I removed the Bitbucket plugin. I already had the bitbucket endpoint set up with the `Manage hooks` selected. It didn't seem to affect/do anything. I deleted it and readded it with no change. I added the webhook path to bitbucket and now it's notifying Jenkins! Thank you @casz !

**Comment by casz** [comment]
Only reason why manage hooks won't work is if your using an credential that does not have access to the repository.

**Comment by mabushey** [comment]
It's the same credentials that's able to pull down the repo and run tests. I appreciate your time to get this figured out very much. :)
