### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by rbywater** [Eernie/bitbucket-webhooks-plugin#67]
Just wondering if I could clarify which license this project is officially signed up to? I see that the LICENSE file seems to be using GPL but then I notice there's a few files that seem to be licensed with the MIT license.

**Comment by casz** [comment]
License is pretty clear, it's GPL v2 as a whole. it cannot be more clear.

Those files with MIT is contribution from contributors, who have it as their default header.
Does it matter that they are there? No, not when the `LICENSE ` specifies otherwise.
