### ISSUE TITLE
duplicate "Webhooks" links in Repo Settings GUI in BB 5.4

### ISSUE THREAD

**Issue by vinylplz** [Eernie/bitbucket-webhooks-plugin#68]
Bitbucket 5.4 ships with it's own built-in "Webhooks" functionality.  When running 5.4 with this "bitbucket-webhooks" plugin installed, there are two "Webhooks" links in the Repository Admin->Workflow section.  This is confusing to users.

![duplicate_webhooks_54bb](https://user-images.githubusercontent.com/1136729/30822896-43f15f7e-a1df-11e7-8117-2992643fcad4.jpg)

I suggest changing the name displayed in the UI here to something like "Webhooks (plugin)" or "Webhooks (BBBS)" (for Jenkins' Bitbucket Branch Source Plugin) to disambiguate it from the built-in Webhooks functionality.

**Comment by casz** [comment]
@vinylplz https://marketplace.atlassian.com/plugins/nl.topicus.bitbucket.bitbucket-webhooks/versions#b100500110

**Comment by vinylplz** [comment]
Awesome.  Many thanks!
