### ISSUE TITLE
Update from 1.4.2 to 1.5.1 fails

### ISSUE THREAD

**Issue by ddraper02** [Eernie/bitbucket-webhooks-plugin#70]
Attempting to update the bitbucket-webhooks from Bitbucket 4.10.1 "Manage Add-ons" gives the error:
 "Problem accessing the file bitbucket-webhooks".  This is happening on two different servers.  I don't see anything in the Bitbucket logs; perhaps I'm not looking in the right place.

**Comment by casz** [comment]
Tried uninstalling the plugin and installing it again?

**Comment by casz** [comment]
Also consider updating: "atlassian universal plugin manager plugin"

**Comment by ddraper02** [comment]
Tried updating the "Atlassian Universal Plugin Manager Plugin" and got a similar error for that.   And everything else I try to update.   So this doesn't appear to be an issue specific to bitbucket-webhooks and we can close this.
