### ISSUE TITLE
Build not triggered when tag created #2

### ISSUE THREAD

**Issue by bb-tle** [Eernie/bitbucket-webhooks-plugin#74]
Bitbucket Server side (5.3.1) : Bitbucket with Post Webhooks (1.5.2)
Jenkins side (2.73.3) : Bitbucket Branch Source plugin (2.2.6)

Today I updated Bitbucket Branch Source plugin to 2.2.6, which is supposed to support building from tags. However it did not build when a new tag was created.
I then turned on access logging for Jenkins and noticed that 1) when "On Push" and "Tag Created" were both selected from Post Webhooks, I could see in the Jenkins access log the line "POST /bitbucket-scmsource-hook/notify HTTP/1.1" 200 0 "-" "Apache-HttpClient/4.5.1 (Java/1.8.0_102)" showing Post Webhooks plugin informed Jenkins of the change. However, if 2) I only enabled "Tag Created" and performed a push, the above log entry did not appear, implying Post Webhooks did not communicate with Jenkins when only tagging was done (?).
In both cases, I modified a file and committed in master branch, created a tag (annotated) and finally used command "git push --follow-tags" to push. Thank you in advance for your insight.

**Comment by casz** [comment]
First off, Bitbucket Branch Source plugin 2.2.6 is non functional as shown by https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/83

**Comment by bb-tle** [comment]
Thank you for letting me know, casz. My concern is also about not seeing communication from Post Webhooks... but again this may be related to 2.2.6 being broken.

**Comment by casz** [comment]
@bb-tle did you resolve your issue?

**Comment by bb-tle** [comment]
Thank you for asking @casz, I did try 2.2.7. I do not think building on tags created is currently supported as yet. Right now we would just go with building on commit push and PR merges.

**Comment by casz** [comment]
@bb-tle tags should be supported now 👍
