### ISSUE TITLE
[feature request] Filter on branch/tag 

### ISSUE THREAD

**Issue by boeboe** [Eernie/bitbucket-webhooks-plugin#75]
Hi,

I would like to be able to create a WebHook that only applies on a certain branch/tag. We have the following CI/CD strategy:
1. feature development happens on a _features/FEAT-1_ branch
2. a Pull request is created on bitbucket towards the _develop_ branch
3. this PR creates a Jenkins pipeline-build through an OpenShift BuildConfig

... once the build is passed, the next phase of merge and deploy start
1. PR is merged
2. de dev branch receives a push which leads to a different pipeline build
3. this pipeline does the deploy and promotions to _DEV_ and _TEST_ environments

FYI, the **HTTP Request Post-Receive Hook** plugin already supports this filtering on branch and tags, but unfortunately doesn't support the extended trigger source (on push, branch delete, PR request created, etc...) this plugin does.

**Comment by casz** [comment]
#71 supports branches and already merged however not released yet.
However tags is a different story.

**Comment by boeboe** [comment]
Super! That's good news... looking forward to the release.

Best regards,
Bart

**Comment by casz** [comment]
@boeboe 
https://marketplace.atlassian.com/plugins/nl.topicus.bitbucket.bitbucket-webhooks/versions#b100600000 released :)
