### ISSUE TITLE
Set HTTP User-Agent

### ISSUE THREAD

**Issue by sj26** [Eernie/bitbucket-webhooks-plugin#76]
It would be super useful if the http client set a user-agent containing this plug-in's name and version so that integrators can identify and support this plug-in:

https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#setUserAgent(java.lang.String)

**Comment by casz** [comment]
@sj26 Pull request are welcome  :relieved:

_Sent from my LG G6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sj26** [comment]
Awesome! I'll see if I can throw something together tomorrow. 🙇
