### ISSUE TITLE
Branch deletion fails to marshal JSON

### ISSUE THREAD

**Issue by sj26** [Eernie/bitbucket-webhooks-plugin#80]
I just deleted a branch with something like `git push origin :foo` and got no webhook but a message in the log:

```
2017-11-28 11:04:12,302 ERROR [threadpool:thread-4] sj26 @YPEPZ5x664x220x0 118.127.108.58,172.17.0.1 "POST /scm/tst/test.git/git-receive-pack HTTP/1.1" n.t.b.api.PullRequestListener [repo: TST/test[1]]| Failed to marshal REPO_PUSH payload to JSON. The event will be discarded
```

**Comment by casz** [comment]
Version 1.6.1?

**Comment by sj26** [comment]
Yes, Bitbucket Server 5.5.2 and addon version 1.6.1.

**Comment by casz** [comment]
well, seeing slightly different error message: `Failed to marshal BRANCH_DELETED payload to JSON. The event will be discarded`

**Comment by casz** [comment]
@sj26 if you want to help debug.
You need to install Atlassian Plugin SDK, https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project
Windows Downloadable: https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-windows
Linux/Mac: has several install options, https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project/install-the-atlassian-sdk-on-a-linux-or-mac-system
You then clone this repo and run `atlas-debug`. You can then set up a remote debug target in idea/eclipse: https://developer.atlassian.com/docs/developer-tools/working-in-an-ide/creating-a-remote-debug-target
