### ISSUE TITLE
Pullrequest rescope event on target commit

### ISSUE THREAD

**Issue by joggeli34** [Eernie/bitbucket-webhooks-plugin#86]
Hi,
Would it be possible to send a rescope-event also on target changes? Probably as a seperate event "re-scoped-to". This allows to allways trigger the current state of the pullrequest when it will be aproved.

**Comment by casz** [comment]
@joggeli34 No, https://community.atlassian.com/t5/Bitbucket-questions/Change-pull-request-refs-after-Commit-instead-of-after-Approval/qaq-p/194702 answers why it shouldn't be done.
