### ISSUE TITLE
Is there any way to get the target branch from a PR in the pipeline DSL

### ISSUE THREAD

**Issue by kristofdepypere** [Eernie/bitbucket-webhooks-plugin#87]
I've been looking hours to have an idea on how to get the target branch specified in the PR being build inside the Pipeline DSL.
Is there anything send using this plugin from bitbucket accessible in a way in the jenkins pipeline dsl ?
I printed all env vars but nothing seems to contain this value.

**Comment by casz** [comment]
if you switch to using the bitbucket source branch plugin you get access to the environment variables provided by the branch API

https://plugins.jenkins.io/cloudbees-bitbucket-branch-source
https://github.com/jenkinsci/branch-api-plugin/blob/28be8058a6faea90f0549b80cce2c24714f69ea4/src/main/java/jenkins/branch/BranchNameContributor.java
