### ISSUE TITLE
Enabling webhooks on a project-level and inheriting it

### ISSUE THREAD

**Issue by ThomasKasene** [Eernie/bitbucket-webhooks-plugin#89]
With the latest versions of BitBucket you can configure many things on a project-level and have the repositories in that project inherit the settings or override them. Is it possible to do something like that with this plugin as well? We have an awful lot of repositories, and it's a pain to register the webhooks manually for each one.

Thanks in advance!

**Comment by casz** [comment]
Jenkins is able to register them for you. The Bitbucket branch source plugin is able to register them for you.
I haven't looked into the inheritance but it should be possible.

**Comment by ThomasKasene** [comment]
My hope and dream was that I could install this plugin on Bitbucket, and the Bitbucket Branch Source Plugin on Jenkins - and get a job automatically created on Jenkins when I create a new Bitbucket repository inside a project that my Organization Folder is watching.

Are you saying that's what would happen, as long as I enable automatic hook management in my Organization Folder configuration on Jenkins?

If that's the case I'll definitely try to persuade the BitBucket admins at work to install the plugin and try it out next week!

**Comment by casz** [comment]
That's our current setup and it is blissful 🍰 So oblivious to new repos being added. All it takes is a single scan and Jenkins will automatically manage the hooks for you.

**Comment by ThomasKasene** [comment]
I managed to try this today, and I can confirm it's working, so for my part, this is no longer a need! Thanks for the info, @casz

**Comment by abishek3876** [comment]
I think this should be reopened... This is still a very nice feature to have for users integrating to other systems (apart from Jenkins) and people who can't grant admin privileges to Jenkins...

**Comment by casz** [comment]
I tried looking at the bitbucket server developer docs and can't really find anything on inheritance unless we change our plugin to work as a hook plugin, which I do not see happening. 
Even Bitbucket server devs own webhook plugin added in 5.4, is not made as project inheritance.
