### ISSUE TITLE
Update webhook settings from Jenkins?

### ISSUE THREAD

**Issue by ThomasKasene** [Eernie/bitbucket-webhooks-plugin#90]
I've recently managed to get this plugin installed at work (and it's amazing, by the way) but looking at the webhook settings, I see there's one called "Committers to ignore". Does the API that the plugin exposes allow Jenkins to customize this field (and the others for that matter) upon webook creation?

If not, then I'd love to see something like this implemented - then the next step would be to get the Bitbucket Source Branch Plugin to use it.

**Comment by ThomasKasene** [comment]
I just realized this is a duplicate of https://github.com/Eernie/bitbucket-webhooks-plugin/issues/37. Closing

**Comment by casz** [comment]
Jenkins will not override commiters to ignore if it is changed after the creation is done by Jenkins, so you should be fine 👍
