### ISSUE TITLE
Pull Request Comment Event not working

### ISSUE THREAD

**Issue by rmohta** [Eernie/bitbucket-webhooks-plugin#91]
When we add a `file comment` or `line comment` for an open PR, we don't see any new builds on Jenkins. 

Job type setup in Jenkins: Multibranch Pipeline
Atlassian Bitbucket v5.2.3

In Settings page, we have the following Pull Request Events enabled
* Pull request created
* Pull request updated
* Pull request re-opened
* Pull request re-scoped
* Pull request commented

**Comment by casz** [comment]
closing in favor of #93 as it requires changes to https://github.com/jenkinsci/bitbucket-branch-source-plugin
