### ISSUE TITLE
Pull Request Comment - Build only on a specific comment

### ISSUE THREAD

**Issue by rmohta** [Eernie/bitbucket-webhooks-plugin#93]
For our use case, we don't want a build job to run for every comment on a PR. But when a specific comment is included then run this job. Stash PR Builder defaults the marker comment as `test this please`.

Reason for this: Let's say as part of our pipeline we would like to run some Selenium test cases on SauceLab Enterprise. Due to some networking issue, it failed. How do we re-trigger the pipeline? A workaround for now is to close and re-open the PR. Can we do it based on a specific comment?

Job type setup in Jenkins: Multibranch Pipeline
Atlassian Bitbucket v5.2.3

In Settings page, we have the following Pull Request Events enabled

Pull request created
Pull request updated
Pull request re-opened
Pull request re-scoped
Pull request commented

**Comment by rmohta** [comment]
Tied to #91

**Comment by casz** [comment]
This requires a change to https://github.com/jenkinsci/bitbucket-branch-source-plugin if you want this feature, I would expect a pull request to both projects.

**Comment by casz** [comment]
@rmohta Please create a issue over at https://issues.jenkins-ci.org/ and set component to bitbucket-branch-source-plugin 👍 or sent a PR their way over at https://github.com/jenkinsci/bitbucket-branch-source-plugin
