### ISSUE TITLE
Add ability to have a whitelist of branches to fire the webhook

### ISSUE THREAD

**Issue by zampettim** [Eernie/bitbucket-webhooks-plugin#95]
In addition to having a list of branch regex patterns that will be ignored, and not fire the webhook, it would be useful to have the reverse, where the regex patterns is the list of branches to fire the webhook, and all other pushes should be ignored.

This is useful in certain models, where one only wants specific branches like the "develop" branch in a GitFlow model, to trigger automatic builds, and to ignore all other pushes. 

I'm working on a PR to add an "Allowed Branches" config item that would take precedence over the "Ignored Branches" configuration if both exist. 

The other option is to add a flag to treat the Branch Regex as "Ignore" or "Allow" and only have a single regex list.

**Comment by casz** [comment]
It is already built in on the Jenkins side. If you have other use cases, build it on the receiving side instead.

**Comment by zampettim** [comment]
The Jenkins plugin will only build the branch that is defined in the job config, not based upon the branch that is target of the commit. Thus, what happens is that Jenkins is defined to build the "develop" branch. With the current capabilities of this plugin, if I push a branch call "foo", and I have not marked that as being ignored, then the plugin triggers the Jenkins build, which builds the "develop" branch. 

What I want to be able to do is to trigger the webhook only when a certain set of branches is pushed to, and then have the Jenkins side build the branch that was pushed. This is how the competing Bitbucket plugin works, and it solves several more problems this way.

**Comment by casz** [comment]
Again not the responsibility of this plugin, if you use [bitbucket branch source plugin](https://github.com/jenkinsci/bitbucket-branch-source-plugin) the options you expect and ignore branches based on regex. You also get access to the several environment variables you can use to define conditions in your Jenkins file like `CHANGE_TARGET`

Here is the list of environment variables: https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/BranchNameContributor.java

**Comment by casz** [comment]
The bitbucket branch source plugin has an include and excludes option for branches but also for repos on the team.

**Comment by casz** [comment]
Closing as this can be solved on Jenkins with the right plugin and the right configuration working together with Jenkins file.
