### ISSUE TITLE
Cannot compile soy templates using atlas-run off of master

### ISSUE THREAD

**Issue by tmdude9586** [Eernie/bitbucket-webhooks-plugin#99]
I'm currently trying to alter this code to support Microsoft Teams webhook formats, however after pulling master, and executing atlas-run, navigating to the repo settings and hitting "post webhook", it errors out, with the console saying that it cannot compile the soy templates.
<img width="1244" alt="screen shot 2018-04-29 at 4 24 42 pm" src="https://user-images.githubusercontent.com/4073001/39410664-054f8134-4bca-11e8-8a4a-13b9f8984976.png">

**Comment by casz** [comment]
Ya I been meaning to revert the rename since I just never actually got it to work trying to install it in actual instance, just rebase to instead: https://github.com/Eernie/bitbucket-webhooks-plugin/commit/2498a4a4cff1c494eb26c5ce519274eeb860faa5

**Comment by casz** [comment]
created #100 which should solve your issue

**Comment by casz** [comment]
@tmdude9586 can you rebase with jenkinsci's master branch? now that #100 is merged
